# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Gyroscope_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import theproto.realtime_data_pb2 as realtime__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Gyroscope_data.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z\007./iwown',
  serialized_pb=b'\n\x14Gyroscope_data.proto\x1a\x13realtime_data.proto\"\x8a\x01\n\x0cHisGyroscope\x12\x1d\n\ntime_stamp\x18\x01 \x02(\x0b\x32\t.DateTime\x12\x1c\n\x14Gyroscope_data_count\x18\x02 \x02(\x07\x12\x13\n\x0bGyroscope_x\x18\x03 \x02(\x0c\x12\x13\n\x0bGyroscope_y\x18\x04 \x02(\x0c\x12\x13\n\x0bGyroscope_z\x18\x05 \x02(\x0c\x42\tZ\x07./iwown'
  ,
  dependencies=[realtime__data__pb2.DESCRIPTOR,])




_HISGYROSCOPE = _descriptor.Descriptor(
  name='HisGyroscope',
  full_name='HisGyroscope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='HisGyroscope.time_stamp', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Gyroscope_data_count', full_name='HisGyroscope.Gyroscope_data_count', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Gyroscope_x', full_name='HisGyroscope.Gyroscope_x', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Gyroscope_y', full_name='HisGyroscope.Gyroscope_y', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Gyroscope_z', full_name='HisGyroscope.Gyroscope_z', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=184,
)

_HISGYROSCOPE.fields_by_name['time_stamp'].message_type = realtime__data__pb2._DATETIME
DESCRIPTOR.message_types_by_name['HisGyroscope'] = _HISGYROSCOPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HisGyroscope = _reflection.GeneratedProtocolMessageType('HisGyroscope', (_message.Message,), {
  'DESCRIPTOR' : _HISGYROSCOPE,
  '__module__' : 'Gyroscope_data_pb2'
  # @@protoc_insertion_point(class_scope:HisGyroscope)
  })
_sym_db.RegisterMessage(HisGyroscope)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
