# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: his_encrypt_rri_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import theproto.realtime_data_pb2 as realtime__data__pb2
import theproto.his_rri_data_pb2 as his__rri__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='his_encrypt_rri_data.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z\007./iwown',
  serialized_pb=b'\n\x1ahis_encrypt_rri_data.proto\x1a\x13realtime_data.proto\x1a\x12his_rri_data.proto\"P\n\rHisRRIEncrypt\x12\x1f\n\nrriencrypt\x18\x01 \x02(\x0b\x32\x0b.HisDataRRI\x12\x0e\n\x06Random\x18\x02 \x02(\x0c\x12\x0e\n\x06\x42leMac\x18\x03 \x02(\x0c\"L\n\x11HisDataRRIEncrypt\x12\x1f\n\x07his_rri\x18\x01 \x02(\x0b\x32\x0e.HisRRIEncrypt\x12\x16\n\x0esignature_data\x18\x02 \x02(\x0c\x42\tZ\x07./iwown'
  ,
  dependencies=[realtime__data__pb2.DESCRIPTOR,his__rri__data__pb2.DESCRIPTOR,])




_HISRRIENCRYPT = _descriptor.Descriptor(
  name='HisRRIEncrypt',
  full_name='HisRRIEncrypt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rriencrypt', full_name='HisRRIEncrypt.rriencrypt', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Random', full_name='HisRRIEncrypt.Random', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BleMac', full_name='HisRRIEncrypt.BleMac', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=151,
)


_HISDATARRIENCRYPT = _descriptor.Descriptor(
  name='HisDataRRIEncrypt',
  full_name='HisDataRRIEncrypt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='his_rri', full_name='HisDataRRIEncrypt.his_rri', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature_data', full_name='HisDataRRIEncrypt.signature_data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=229,
)

_HISRRIENCRYPT.fields_by_name['rriencrypt'].message_type = his__rri__data__pb2._HISDATARRI
_HISDATARRIENCRYPT.fields_by_name['his_rri'].message_type = _HISRRIENCRYPT
DESCRIPTOR.message_types_by_name['HisRRIEncrypt'] = _HISRRIENCRYPT
DESCRIPTOR.message_types_by_name['HisDataRRIEncrypt'] = _HISDATARRIENCRYPT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HisRRIEncrypt = _reflection.GeneratedProtocolMessageType('HisRRIEncrypt', (_message.Message,), {
  'DESCRIPTOR' : _HISRRIENCRYPT,
  '__module__' : 'his_encrypt_rri_data_pb2'
  # @@protoc_insertion_point(class_scope:HisRRIEncrypt)
  })
_sym_db.RegisterMessage(HisRRIEncrypt)

HisDataRRIEncrypt = _reflection.GeneratedProtocolMessageType('HisDataRRIEncrypt', (_message.Message,), {
  'DESCRIPTOR' : _HISDATARRIENCRYPT,
  '__module__' : 'his_encrypt_rri_data_pb2'
  # @@protoc_insertion_point(class_scope:HisDataRRIEncrypt)
  })
_sym_db.RegisterMessage(HisDataRRIEncrypt)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
