# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: his_rri_data_v2.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import theproto.realtime_data_pb2 as realtime__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='his_rri_data_v2.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z\007./iwown',
  serialized_pb=b'\n\x15his_rri_data_v2.proto\x1a\x13realtime_data.proto\"@\n\rHisDataRRI_v2\x12\x1d\n\ntime_stamp\x18\x01 \x02(\x0b\x32\t.DateTime\x12\x10\n\x08raw_data\x18\x02 \x02(\x0c\x42\tZ\x07./iwown'
  ,
  dependencies=[realtime__data__pb2.DESCRIPTOR,])




_HISDATARRI_V2 = _descriptor.Descriptor(
  name='HisDataRRI_v2',
  full_name='HisDataRRI_v2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='HisDataRRI_v2.time_stamp', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_data', full_name='HisDataRRI_v2.raw_data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=110,
)

_HISDATARRI_V2.fields_by_name['time_stamp'].message_type = realtime__data__pb2._DATETIME
DESCRIPTOR.message_types_by_name['HisDataRRI_v2'] = _HISDATARRI_V2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HisDataRRI_v2 = _reflection.GeneratedProtocolMessageType('HisDataRRI_v2', (_message.Message,), {
  'DESCRIPTOR' : _HISDATARRI_V2,
  '__module__' : 'his_rri_data_v2_pb2'
  # @@protoc_insertion_point(class_scope:HisDataRRI_v2)
  })
_sym_db.RegisterMessage(HisDataRRI_v2)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
