# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: his_spo2_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import theproto.realtime_data_pb2 as realtime__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='his_spo2_data.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z\007./iwown',
  serialized_pb=b'\n\x13his_spo2_data.proto\x1a\x13realtime_data.proto\"?\n\x0bHisDataSpo2\x12\x1d\n\ntime_stamp\x18\x01 \x02(\x0b\x32\t.DateTime\x12\x11\n\tspo2_data\x18\x02 \x03(\x07\x42\tZ\x07./iwown'
  ,
  dependencies=[realtime__data__pb2.DESCRIPTOR,])




_HISDATASPO2 = _descriptor.Descriptor(
  name='HisDataSpo2',
  full_name='HisDataSpo2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='HisDataSpo2.time_stamp', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spo2_data', full_name='HisDataSpo2.spo2_data', index=1,
      number=2, type=7, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=107,
)

_HISDATASPO2.fields_by_name['time_stamp'].message_type = realtime__data__pb2._DATETIME
DESCRIPTOR.message_types_by_name['HisDataSpo2'] = _HISDATASPO2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HisDataSpo2 = _reflection.GeneratedProtocolMessageType('HisDataSpo2', (_message.Message,), {
  'DESCRIPTOR' : _HISDATASPO2,
  '__module__' : 'his_spo2_data_pb2'
  # @@protoc_insertion_point(class_scope:HisDataSpo2)
  })
_sym_db.RegisterMessage(HisDataSpo2)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
