# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: his_encrypt_ppg_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import theproto.realtime_data_pb2 as realtime__data__pb2
import theproto.his_ppg_data_pb2 as his__ppg__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='his_encrypt_ppg_data.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z\007./iwown',
  serialized_pb=b'\n\x1ahis_encrypt_ppg_data.proto\x1a\x13realtime_data.proto\x1a\x12his_ppg_data.proto\"P\n\rHisPPGEncrypt\x12\x1f\n\nppgencrypt\x18\x01 \x02(\x0b\x32\x0b.HisDataPPG\x12\x0e\n\x06Random\x18\x02 \x02(\x0c\x12\x0e\n\x06\x42leMac\x18\x03 \x02(\x0c\"L\n\x11HisDataPPGEncrypt\x12\x1f\n\x07his_ppg\x18\x01 \x02(\x0b\x32\x0e.HisPPGEncrypt\x12\x16\n\x0esignature_data\x18\x02 \x02(\x0c\x42\tZ\x07./iwown'
  ,
  dependencies=[realtime__data__pb2.DESCRIPTOR,his__ppg__data__pb2.DESCRIPTOR,])




_HISPPGENCRYPT = _descriptor.Descriptor(
  name='HisPPGEncrypt',
  full_name='HisPPGEncrypt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ppgencrypt', full_name='HisPPGEncrypt.ppgencrypt', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Random', full_name='HisPPGEncrypt.Random', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BleMac', full_name='HisPPGEncrypt.BleMac', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=151,
)


_HISDATAPPGENCRYPT = _descriptor.Descriptor(
  name='HisDataPPGEncrypt',
  full_name='HisDataPPGEncrypt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='his_ppg', full_name='HisDataPPGEncrypt.his_ppg', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature_data', full_name='HisDataPPGEncrypt.signature_data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=229,
)

_HISPPGENCRYPT.fields_by_name['ppgencrypt'].message_type = his__ppg__data__pb2._HISDATAPPG
_HISDATAPPGENCRYPT.fields_by_name['his_ppg'].message_type = _HISPPGENCRYPT
DESCRIPTOR.message_types_by_name['HisPPGEncrypt'] = _HISPPGENCRYPT
DESCRIPTOR.message_types_by_name['HisDataPPGEncrypt'] = _HISDATAPPGENCRYPT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HisPPGEncrypt = _reflection.GeneratedProtocolMessageType('HisPPGEncrypt', (_message.Message,), {
  'DESCRIPTOR' : _HISPPGENCRYPT,
  '__module__' : 'his_encrypt_ppg_data_pb2'
  # @@protoc_insertion_point(class_scope:HisPPGEncrypt)
  })
_sym_db.RegisterMessage(HisPPGEncrypt)

HisDataPPGEncrypt = _reflection.GeneratedProtocolMessageType('HisDataPPGEncrypt', (_message.Message,), {
  'DESCRIPTOR' : _HISDATAPPGENCRYPT,
  '__module__' : 'his_encrypt_ppg_data_pb2'
  # @@protoc_insertion_point(class_scope:HisDataPPGEncrypt)
  })
_sym_db.RegisterMessage(HisDataPPGEncrypt)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
