# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: his_temperature_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import theproto.realtime_data_pb2 as realtime__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='his_temperature_data.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z\007./iwown',
  serialized_pb=b'\n\x1ahis_temperature_data.proto\x1a\x13realtime_data.proto\"0\n\nSensorTemp\x12\x10\n\x08\x65vi_body\x18\x01 \x02(\x07\x12\x10\n\x08\x65sti_arm\x18\x02 \x02(\x07\"U\n\x12HisDataTemperature\x12\x1d\n\ntime_stamp\x18\x01 \x02(\x0b\x32\t.DateTime\x12 \n\x0btemperature\x18\x02 \x02(\x0b\x32\x0b.SensorTempB\tZ\x07./iwown'
  ,
  dependencies=[realtime__data__pb2.DESCRIPTOR,])




_SENSORTEMP = _descriptor.Descriptor(
  name='SensorTemp',
  full_name='SensorTemp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='evi_body', full_name='SensorTemp.evi_body', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='esti_arm', full_name='SensorTemp.esti_arm', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=99,
)


_HISDATATEMPERATURE = _descriptor.Descriptor(
  name='HisDataTemperature',
  full_name='HisDataTemperature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='HisDataTemperature.time_stamp', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='HisDataTemperature.temperature', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=186,
)

_HISDATATEMPERATURE.fields_by_name['time_stamp'].message_type = realtime__data__pb2._DATETIME
_HISDATATEMPERATURE.fields_by_name['temperature'].message_type = _SENSORTEMP
DESCRIPTOR.message_types_by_name['SensorTemp'] = _SENSORTEMP
DESCRIPTOR.message_types_by_name['HisDataTemperature'] = _HISDATATEMPERATURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorTemp = _reflection.GeneratedProtocolMessageType('SensorTemp', (_message.Message,), {
  'DESCRIPTOR' : _SENSORTEMP,
  '__module__' : 'his_temperature_data_pb2'
  # @@protoc_insertion_point(class_scope:SensorTemp)
  })
_sym_db.RegisterMessage(SensorTemp)

HisDataTemperature = _reflection.GeneratedProtocolMessageType('HisDataTemperature', (_message.Message,), {
  'DESCRIPTOR' : _HISDATATEMPERATURE,
  '__module__' : 'his_temperature_data_pb2'
  # @@protoc_insertion_point(class_scope:HisDataTemperature)
  })
_sym_db.RegisterMessage(HisDataTemperature)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
