# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThirdParty_health_data_V2.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import theproto.realtime_data_pb2 as realtime__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ThirdParty_health_data_V2.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z\007./iwown',
  serialized_pb=b'\n\x1fThirdParty_health_data_V2.proto\x1a\x13realtime_data.proto\"U\n\x12MattressDataHealth\x12\x1a\n\x12Physical_SignsData\x18\x01 \x02(\x0c\x12#\n\x10\x41\x63quisition_time\x18\x02 \x02(\x0b\x32\t.DateTime\"J\n\x13HisDataThirdPartyV2\x12+\n\x0cMattressData\x18\x01 \x01(\x0b\x32\x13.MattressDataHealthH\x00\x42\x06\n\x04\x64\x61taB\tZ\x07./iwown'
  ,
  dependencies=[realtime__data__pb2.DESCRIPTOR,])




_MATTRESSDATAHEALTH = _descriptor.Descriptor(
  name='MattressDataHealth',
  full_name='MattressDataHealth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Physical_SignsData', full_name='MattressDataHealth.Physical_SignsData', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Acquisition_time', full_name='MattressDataHealth.Acquisition_time', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=141,
)


_HISDATATHIRDPARTYV2 = _descriptor.Descriptor(
  name='HisDataThirdPartyV2',
  full_name='HisDataThirdPartyV2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MattressData', full_name='HisDataThirdPartyV2.MattressData', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='HisDataThirdPartyV2.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=143,
  serialized_end=217,
)

_MATTRESSDATAHEALTH.fields_by_name['Acquisition_time'].message_type = realtime__data__pb2._DATETIME
_HISDATATHIRDPARTYV2.fields_by_name['MattressData'].message_type = _MATTRESSDATAHEALTH
_HISDATATHIRDPARTYV2.oneofs_by_name['data'].fields.append(
  _HISDATATHIRDPARTYV2.fields_by_name['MattressData'])
_HISDATATHIRDPARTYV2.fields_by_name['MattressData'].containing_oneof = _HISDATATHIRDPARTYV2.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['MattressDataHealth'] = _MATTRESSDATAHEALTH
DESCRIPTOR.message_types_by_name['HisDataThirdPartyV2'] = _HISDATATHIRDPARTYV2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MattressDataHealth = _reflection.GeneratedProtocolMessageType('MattressDataHealth', (_message.Message,), {
  'DESCRIPTOR' : _MATTRESSDATAHEALTH,
  '__module__' : 'ThirdParty_health_data_V2_pb2'
  # @@protoc_insertion_point(class_scope:MattressDataHealth)
  })
_sym_db.RegisterMessage(MattressDataHealth)

HisDataThirdPartyV2 = _reflection.GeneratedProtocolMessageType('HisDataThirdPartyV2', (_message.Message,), {
  'DESCRIPTOR' : _HISDATATHIRDPARTYV2,
  '__module__' : 'ThirdParty_health_data_V2_pb2'
  # @@protoc_insertion_point(class_scope:HisDataThirdPartyV2)
  })
_sym_db.RegisterMessage(HisDataThirdPartyV2)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
