# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ACCelerometer_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import theproto.realtime_data_pb2 as realtime__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ACCelerometer_data.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z\007./iwown',
  serialized_pb=b'\n\x18\x41\x43\x43\x65lerometer_data.proto\x1a\x13realtime_data.proto\"v\n\x10HisACCelerometer\x12\x1d\n\ntime_stamp\x18\x01 \x02(\x0b\x32\t.DateTime\x12\x16\n\x0e\x61\x63\x63_data_count\x18\x02 \x02(\x07\x12\r\n\x05\x61\x63\x63_x\x18\x03 \x02(\x0c\x12\r\n\x05\x61\x63\x63_y\x18\x04 \x02(\x0c\x12\r\n\x05\x61\x63\x63_z\x18\x05 \x02(\x0c\x42\tZ\x07./iwown'
  ,
  dependencies=[realtime__data__pb2.DESCRIPTOR,])




_HISACCELEROMETER = _descriptor.Descriptor(
  name='HisACCelerometer',
  full_name='HisACCelerometer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='HisACCelerometer.time_stamp', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acc_data_count', full_name='HisACCelerometer.acc_data_count', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acc_x', full_name='HisACCelerometer.acc_x', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acc_y', full_name='HisACCelerometer.acc_y', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acc_z', full_name='HisACCelerometer.acc_z', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=167,
)

_HISACCELEROMETER.fields_by_name['time_stamp'].message_type = realtime__data__pb2._DATETIME
DESCRIPTOR.message_types_by_name['HisACCelerometer'] = _HISACCELEROMETER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HisACCelerometer = _reflection.GeneratedProtocolMessageType('HisACCelerometer', (_message.Message,), {
  'DESCRIPTOR' : _HISACCELEROMETER,
  '__module__' : 'ACCelerometer_data_pb2'
  # @@protoc_insertion_point(class_scope:HisACCelerometer)
  })
_sym_db.RegisterMessage(HisACCelerometer)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
