# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: his_multi_leads_ecg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import theproto.realtime_data_pb2 as realtime__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='his_multi_leads_ecg.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z\007./iwown',
  serialized_pb=b'\n\x19his_multi_leads_ecg.proto\x1a\x13realtime_data.proto\"\x81\x01\n\x14HisDataMultiLeadsECG\x12\x1d\n\ntime_stamp\x18\x01 \x02(\x0b\x32\t.DateTime\x12\x1a\n\x12Number_of_channels\x18\x02 \x02(\x07\x12\x1c\n\x14Single_data_byte_len\x18\x03 \x02(\x07\x12\x10\n\x08raw_data\x18\x04 \x02(\x0c\x42\tZ\x07./iwown'
  ,
  dependencies=[realtime__data__pb2.DESCRIPTOR,])




_HISDATAMULTILEADSECG = _descriptor.Descriptor(
  name='HisDataMultiLeadsECG',
  full_name='HisDataMultiLeadsECG',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='HisDataMultiLeadsECG.time_stamp', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Number_of_channels', full_name='HisDataMultiLeadsECG.Number_of_channels', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Single_data_byte_len', full_name='HisDataMultiLeadsECG.Single_data_byte_len', index=2,
      number=3, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_data', full_name='HisDataMultiLeadsECG.raw_data', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=180,
)

_HISDATAMULTILEADSECG.fields_by_name['time_stamp'].message_type = realtime__data__pb2._DATETIME
DESCRIPTOR.message_types_by_name['HisDataMultiLeadsECG'] = _HISDATAMULTILEADSECG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HisDataMultiLeadsECG = _reflection.GeneratedProtocolMessageType('HisDataMultiLeadsECG', (_message.Message,), {
  'DESCRIPTOR' : _HISDATAMULTILEADSECG,
  '__module__' : 'his_multi_leads_ecg_pb2'
  # @@protoc_insertion_point(class_scope:HisDataMultiLeadsECG)
  })
_sym_db.RegisterMessage(HisDataMultiLeadsECG)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
