# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: his_encrypt_health_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import theproto.realtime_data_pb2 as realtime__data__pb2
import theproto.his_health_data_pb2 as his__health__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='his_encrypt_health_data.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z\007./iwown',
  serialized_pb=b'\n\x1dhis_encrypt_health_data.proto\x1a\x13realtime_data.proto\x1a\x15his_health_data.proto\"R\n\x10HisHealthEncrypt\x12\x1e\n\x06health\x18\x01 \x02(\x0b\x32\x0e.HisDataHealth\x12\x0e\n\x06Random\x18\x02 \x02(\x0c\x12\x0e\n\x06\x42leMac\x18\x03 \x02(\x0c\"U\n\x14HisDataHealthEncrypt\x12%\n\nhis_Health\x18\x01 \x02(\x0b\x32\x11.HisHealthEncrypt\x12\x16\n\x0esignature_data\x18\x02 \x02(\x0c\x42\tZ\x07./iwown'
  ,
  dependencies=[realtime__data__pb2.DESCRIPTOR,his__health__data__pb2.DESCRIPTOR,])




_HISHEALTHENCRYPT = _descriptor.Descriptor(
  name='HisHealthEncrypt',
  full_name='HisHealthEncrypt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='health', full_name='HisHealthEncrypt.health', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Random', full_name='HisHealthEncrypt.Random', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BleMac', full_name='HisHealthEncrypt.BleMac', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=159,
)


_HISDATAHEALTHENCRYPT = _descriptor.Descriptor(
  name='HisDataHealthEncrypt',
  full_name='HisDataHealthEncrypt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='his_Health', full_name='HisDataHealthEncrypt.his_Health', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature_data', full_name='HisDataHealthEncrypt.signature_data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=246,
)

_HISHEALTHENCRYPT.fields_by_name['health'].message_type = his__health__data__pb2._HISDATAHEALTH
_HISDATAHEALTHENCRYPT.fields_by_name['his_Health'].message_type = _HISHEALTHENCRYPT
DESCRIPTOR.message_types_by_name['HisHealthEncrypt'] = _HISHEALTHENCRYPT
DESCRIPTOR.message_types_by_name['HisDataHealthEncrypt'] = _HISDATAHEALTHENCRYPT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HisHealthEncrypt = _reflection.GeneratedProtocolMessageType('HisHealthEncrypt', (_message.Message,), {
  'DESCRIPTOR' : _HISHEALTHENCRYPT,
  '__module__' : 'his_encrypt_health_data_pb2'
  # @@protoc_insertion_point(class_scope:HisHealthEncrypt)
  })
_sym_db.RegisterMessage(HisHealthEncrypt)

HisDataHealthEncrypt = _reflection.GeneratedProtocolMessageType('HisDataHealthEncrypt', (_message.Message,), {
  'DESCRIPTOR' : _HISDATAHEALTHENCRYPT,
  '__module__' : 'his_encrypt_health_data_pb2'
  # @@protoc_insertion_point(class_scope:HisDataHealthEncrypt)
  })
_sym_db.RegisterMessage(HisDataHealthEncrypt)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
