# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: his_medic_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import theproto.realtime_data_pb2 as realtime__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='his_medic_data.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z\007./iwown',
  serialized_pb=b'\n\x14his_medic_data.proto\x1a\x13realtime_data.proto\"\x81\x01\n\x0cHisDataMedic\x12\x1d\n\ntime_stamp\x18\x01 \x02(\x0b\x32\t.DateTime\x12\x12\n\npain_level\x18\x02 \x01(\x07\x12\x15\n\rfatigue_level\x18\x03 \x01(\x07\x12\x13\n\x0bstiff_level\x18\x04 \x01(\x07\x12\x12\n\nstiff_time\x18\x05 \x01(\x07\x42\tZ\x07./iwown'
  ,
  dependencies=[realtime__data__pb2.DESCRIPTOR,])




_HISDATAMEDIC = _descriptor.Descriptor(
  name='HisDataMedic',
  full_name='HisDataMedic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='HisDataMedic.time_stamp', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pain_level', full_name='HisDataMedic.pain_level', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fatigue_level', full_name='HisDataMedic.fatigue_level', index=2,
      number=3, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stiff_level', full_name='HisDataMedic.stiff_level', index=3,
      number=4, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stiff_time', full_name='HisDataMedic.stiff_time', index=4,
      number=5, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=175,
)

_HISDATAMEDIC.fields_by_name['time_stamp'].message_type = realtime__data__pb2._DATETIME
DESCRIPTOR.message_types_by_name['HisDataMedic'] = _HISDATAMEDIC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HisDataMedic = _reflection.GeneratedProtocolMessageType('HisDataMedic', (_message.Message,), {
  'DESCRIPTOR' : _HISDATAMEDIC,
  '__module__' : 'his_medic_data_pb2'
  # @@protoc_insertion_point(class_scope:HisDataMedic)
  })
_sym_db.RegisterMessage(HisDataMedic)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
