# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: his_ecg_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import theproto.realtime_data_pb2 as realtime__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='his_ecg_data.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z\007./iwown',
  serialized_pb=b'\n\x12his_ecg_data.proto\x1a\x13realtime_data.proto\"A\n\nHisDataECG\x12\x1d\n\ntime_stamp\x18\x01 \x02(\x0b\x32\t.DateTime\x12\x14\n\x08raw_data\x18\x02 \x03(\x0f\x42\x02\x10\x01\x42\tZ\x07./iwown'
  ,
  dependencies=[realtime__data__pb2.DESCRIPTOR,])




_HISDATAECG = _descriptor.Descriptor(
  name='HisDataECG',
  full_name='HisDataECG',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='HisDataECG.time_stamp', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_data', full_name='HisDataECG.raw_data', index=1,
      number=2, type=15, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=108,
)

_HISDATAECG.fields_by_name['time_stamp'].message_type = realtime__data__pb2._DATETIME
DESCRIPTOR.message_types_by_name['HisDataECG'] = _HISDATAECG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HisDataECG = _reflection.GeneratedProtocolMessageType('HisDataECG', (_message.Message,), {
  'DESCRIPTOR' : _HISDATAECG,
  '__module__' : 'his_ecg_data_pb2'
  # @@protoc_insertion_point(class_scope:HisDataECG)
  })
_sym_db.RegisterMessage(HisDataECG)


DESCRIPTOR._options = None
_HISDATAECG.fields_by_name['raw_data']._options = None
# @@protoc_insertion_point(module_scope)
