# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: his_encrypt_ecg_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import theproto.realtime_data_pb2 as realtime__data__pb2
import theproto.his_ecg_data_pb2 as his__ecg__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='his_encrypt_ecg_data.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z\007./iwown',
  serialized_pb=b'\n\x1ahis_encrypt_ecg_data.proto\x1a\x13realtime_data.proto\x1a\x12his_ecg_data.proto\"P\n\rHisECGEncrypt\x12\x1f\n\necgencrypt\x18\x01 \x02(\x0b\x32\x0b.HisDataECG\x12\x0e\n\x06Random\x18\x02 \x02(\x0c\x12\x0e\n\x06\x42leMac\x18\x03 \x02(\x0c\"L\n\x11HisDataECGEncrypt\x12\x1f\n\x07his_ecg\x18\x01 \x02(\x0b\x32\x0e.HisECGEncrypt\x12\x16\n\x0esignature_data\x18\x02 \x02(\x0c\x42\tZ\x07./iwown'
  ,
  dependencies=[realtime__data__pb2.DESCRIPTOR,his__ecg__data__pb2.DESCRIPTOR,])




_HISECGENCRYPT = _descriptor.Descriptor(
  name='HisECGEncrypt',
  full_name='HisECGEncrypt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ecgencrypt', full_name='HisECGEncrypt.ecgencrypt', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Random', full_name='HisECGEncrypt.Random', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BleMac', full_name='HisECGEncrypt.BleMac', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=151,
)


_HISDATAECGENCRYPT = _descriptor.Descriptor(
  name='HisDataECGEncrypt',
  full_name='HisDataECGEncrypt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='his_ecg', full_name='HisDataECGEncrypt.his_ecg', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature_data', full_name='HisDataECGEncrypt.signature_data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=229,
)

_HISECGENCRYPT.fields_by_name['ecgencrypt'].message_type = his__ecg__data__pb2._HISDATAECG
_HISDATAECGENCRYPT.fields_by_name['his_ecg'].message_type = _HISECGENCRYPT
DESCRIPTOR.message_types_by_name['HisECGEncrypt'] = _HISECGENCRYPT
DESCRIPTOR.message_types_by_name['HisDataECGEncrypt'] = _HISDATAECGENCRYPT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HisECGEncrypt = _reflection.GeneratedProtocolMessageType('HisECGEncrypt', (_message.Message,), {
  'DESCRIPTOR' : _HISECGENCRYPT,
  '__module__' : 'his_encrypt_ecg_data_pb2'
  # @@protoc_insertion_point(class_scope:HisECGEncrypt)
  })
_sym_db.RegisterMessage(HisECGEncrypt)

HisDataECGEncrypt = _reflection.GeneratedProtocolMessageType('HisDataECGEncrypt', (_message.Message,), {
  'DESCRIPTOR' : _HISDATAECGENCRYPT,
  '__module__' : 'his_encrypt_ecg_data_pb2'
  # @@protoc_insertion_point(class_scope:HisDataECGEncrypt)
  })
_sym_db.RegisterMessage(HisDataECGEncrypt)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
