# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: his_swim_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import theproto.realtime_data_pb2 as realtime__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='his_swim_data.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z\007./iwown',
  serialized_pb=b'\n\x13his_swim_data.proto\x1a\x13realtime_data.proto\",\n\tSensorVec\x12\t\n\x01x\x18\x01 \x02(\x07\x12\t\n\x01y\x18\x02 \x02(\x07\x12\t\n\x01z\x18\x03 \x02(\x07\"m\n\x0bHisDataSwim\x12\x1d\n\ntime_stamp\x18\x01 \x02(\x0b\x32\t.DateTime\x12!\n\racc_gyro_data\x18\x02 \x03(\x0b\x32\n.SensorVec\x12\x1c\n\x08mag_data\x18\x03 \x02(\x0b\x32\n.SensorVecB\tZ\x07./iwown'
  ,
  dependencies=[realtime__data__pb2.DESCRIPTOR,])




_SENSORVEC = _descriptor.Descriptor(
  name='SensorVec',
  full_name='SensorVec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='SensorVec.x', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='SensorVec.y', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='SensorVec.z', index=2,
      number=3, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=88,
)


_HISDATASWIM = _descriptor.Descriptor(
  name='HisDataSwim',
  full_name='HisDataSwim',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='HisDataSwim.time_stamp', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acc_gyro_data', full_name='HisDataSwim.acc_gyro_data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mag_data', full_name='HisDataSwim.mag_data', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=199,
)

_HISDATASWIM.fields_by_name['time_stamp'].message_type = realtime__data__pb2._DATETIME
_HISDATASWIM.fields_by_name['acc_gyro_data'].message_type = _SENSORVEC
_HISDATASWIM.fields_by_name['mag_data'].message_type = _SENSORVEC
DESCRIPTOR.message_types_by_name['SensorVec'] = _SENSORVEC
DESCRIPTOR.message_types_by_name['HisDataSwim'] = _HISDATASWIM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorVec = _reflection.GeneratedProtocolMessageType('SensorVec', (_message.Message,), {
  'DESCRIPTOR' : _SENSORVEC,
  '__module__' : 'his_swim_data_pb2'
  # @@protoc_insertion_point(class_scope:SensorVec)
  })
_sym_db.RegisterMessage(SensorVec)

HisDataSwim = _reflection.GeneratedProtocolMessageType('HisDataSwim', (_message.Message,), {
  'DESCRIPTOR' : _HISDATASWIM,
  '__module__' : 'his_swim_data_pb2'
  # @@protoc_insertion_point(class_scope:HisDataSwim)
  })
_sym_db.RegisterMessage(HisDataSwim)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
