# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yyl_info.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yyl_info.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z\007./iwown',
  serialized_pb=b'\n\x0eyyl_info.proto\",\n\x0fyyl_wuqi_report\x12\n\n\x02wq\x18\x01 \x02(\x0c\x12\r\n\x05score\x18\x02 \x02(\x0c\"_\n\x0fyyl_body_report\x12\x0f\n\x07tz_name\x18\x01 \x02(\x0c\x12\x10\n\x08tz_score\x18\x02 \x02(\x0c\x12\x13\n\x0bpre_tz_name\x18\x03 \x02(\x0c\x12\x14\n\x0cpre_tz_score\x18\x04 \x02(\x0c\"G\n\nyyl_notify\x12\x12\n\nhas_report\x18\x01 \x01(\x08\x12%\n\x0breport_type\x18\x02 \x01(\x0e\x32\x10.yyl_report_type\"m\n\x0byyl_Command\x12\x10\n\x08modeling\x18\x01 \x01(\x08\x12%\n\x0bwuqi_report\x18\x04 \x01(\x0b\x32\x10.yyl_wuqi_report\x12%\n\x0b\x62ody_report\x18\x05 \x01(\x0b\x32\x10.yyl_body_report*=\n\x0fyyl_report_type\x12\x13\n\x0fYYL_REPORT_AUTO\x10\x00\x12\x15\n\x11YYL_REPORT_MANUAL\x10\x01\x42\tZ\x07./iwown'
)

_YYL_REPORT_TYPE = _descriptor.EnumDescriptor(
  name='yyl_report_type',
  full_name='yyl_report_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='YYL_REPORT_AUTO', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='YYL_REPORT_MANUAL', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=345,
  serialized_end=406,
)
_sym_db.RegisterEnumDescriptor(_YYL_REPORT_TYPE)

yyl_report_type = enum_type_wrapper.EnumTypeWrapper(_YYL_REPORT_TYPE)
YYL_REPORT_AUTO = 0
YYL_REPORT_MANUAL = 1



_YYL_WUQI_REPORT = _descriptor.Descriptor(
  name='yyl_wuqi_report',
  full_name='yyl_wuqi_report',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wq', full_name='yyl_wuqi_report.wq', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='yyl_wuqi_report.score', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=62,
)


_YYL_BODY_REPORT = _descriptor.Descriptor(
  name='yyl_body_report',
  full_name='yyl_body_report',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tz_name', full_name='yyl_body_report.tz_name', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tz_score', full_name='yyl_body_report.tz_score', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pre_tz_name', full_name='yyl_body_report.pre_tz_name', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pre_tz_score', full_name='yyl_body_report.pre_tz_score', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=159,
)


_YYL_NOTIFY = _descriptor.Descriptor(
  name='yyl_notify',
  full_name='yyl_notify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='has_report', full_name='yyl_notify.has_report', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='report_type', full_name='yyl_notify.report_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=232,
)


_YYL_COMMAND = _descriptor.Descriptor(
  name='yyl_Command',
  full_name='yyl_Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='modeling', full_name='yyl_Command.modeling', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wuqi_report', full_name='yyl_Command.wuqi_report', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body_report', full_name='yyl_Command.body_report', index=2,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=343,
)

_YYL_NOTIFY.fields_by_name['report_type'].enum_type = _YYL_REPORT_TYPE
_YYL_COMMAND.fields_by_name['wuqi_report'].message_type = _YYL_WUQI_REPORT
_YYL_COMMAND.fields_by_name['body_report'].message_type = _YYL_BODY_REPORT
DESCRIPTOR.message_types_by_name['yyl_wuqi_report'] = _YYL_WUQI_REPORT
DESCRIPTOR.message_types_by_name['yyl_body_report'] = _YYL_BODY_REPORT
DESCRIPTOR.message_types_by_name['yyl_notify'] = _YYL_NOTIFY
DESCRIPTOR.message_types_by_name['yyl_Command'] = _YYL_COMMAND
DESCRIPTOR.enum_types_by_name['yyl_report_type'] = _YYL_REPORT_TYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

yyl_wuqi_report = _reflection.GeneratedProtocolMessageType('yyl_wuqi_report', (_message.Message,), {
  'DESCRIPTOR' : _YYL_WUQI_REPORT,
  '__module__' : 'yyl_info_pb2'
  # @@protoc_insertion_point(class_scope:yyl_wuqi_report)
  })
_sym_db.RegisterMessage(yyl_wuqi_report)

yyl_body_report = _reflection.GeneratedProtocolMessageType('yyl_body_report', (_message.Message,), {
  'DESCRIPTOR' : _YYL_BODY_REPORT,
  '__module__' : 'yyl_info_pb2'
  # @@protoc_insertion_point(class_scope:yyl_body_report)
  })
_sym_db.RegisterMessage(yyl_body_report)

yyl_notify = _reflection.GeneratedProtocolMessageType('yyl_notify', (_message.Message,), {
  'DESCRIPTOR' : _YYL_NOTIFY,
  '__module__' : 'yyl_info_pb2'
  # @@protoc_insertion_point(class_scope:yyl_notify)
  })
_sym_db.RegisterMessage(yyl_notify)

yyl_Command = _reflection.GeneratedProtocolMessageType('yyl_Command', (_message.Message,), {
  'DESCRIPTOR' : _YYL_COMMAND,
  '__module__' : 'yyl_info_pb2'
  # @@protoc_insertion_point(class_scope:yyl_Command)
  })
_sym_db.RegisterMessage(yyl_Command)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
